# Generated by Django 4.2.2 on 2023-07-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_choice_question_subject_delete_quesmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Question_text',
            new_name='question_text',
        ),
    ]
