# Generated by Django 4.2.2 on 2023-07-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_result'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
